# Generated by Django 4.2 on 2023-04-24 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voteapp', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='voteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('first_image', models.ImageField(upload_to='upload/votes_images')),
                ('second_image', models.ImageField(upload_to='upload/vote_images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.userprofile')),
                ('vote_image_first', models.ManyToManyField(blank=True, related_name='vote_one', to='voteapp.userprofile')),
                ('vote_image_second', models.ManyToManyField(blank=True, related_name='vote_second', to='voteapp.userprofile')),
            ],
        ),
    ]
