# Generated by Django 4.2 on 2023-04-24 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0003_alter_userprofile_followers_voteimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteimages',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
