# Generated by Django 4.2 on 2023-04-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0005_voteimages_vote_count_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteimages',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='voteapp.userprofile'),
        ),
    ]
