# Generated by Django 4.2 on 2023-04-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0006_alter_voteimages_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteimages',
            name='second_image',
            field=models.ImageField(upload_to='upload/votes_images'),
        ),
    ]
