# Generated by Django 4.2 on 2023-05-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='upload/profile_pictures'),
        ),
    ]
