# Generated by Django 4.2 on 2023-05-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_has_seen',
            field=models.BooleanField(default=False),
        ),
    ]
