# Generated by Django 4.2 on 2023-06-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0016_notification_user_has_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='upload/default.png', upload_to='upload/profile_pictures'),
        ),
    ]
